Move steps

diff --git a/.github/workflows/jitbit-deploy-environment-reusable-test-version.yml b/.github/workflows/jitbit-deploy-environment-reusable-test-version.yml
--- a/.github/workflows/jitbit-deploy-environment-reusable-test-version.yml
+++ b/.github/workflows/jitbit-deploy-environment-reusable-test-version.yml
@@ -210,55 +210,6 @@ jobs:
             echo "| **Active** | \`${ACTIVE_COLOUR}\` | \`${{ inputs.deployment_colour }}\` |"
           } >> "$GITHUB_STEP_SUMMARY"
 
-  plan:
-    name: Plan - ${{ inputs.environment }}
-    runs-on: ubuntu-latest
-    needs: display-versions
-    outputs:
-      plan_exitcode: "${{ steps.plan.outputs.exitcode }}"
-    environment: ${{ inputs.environment }}-plan
-    strategy:
-      fail-fast: false
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
-        with:
-          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd"
-          role-session-name: "hmpps-cr-ancillary-jitbit-app-${{ github.run_number }}"
-          aws-region: "eu-west-2"
-
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
-        with:
-          terraform_version: "1.10.0"
-          terraform_wrapper: false
-
-      - name: Terraform Init
-        working-directory: terraform
-        run: |
-          terraform --version
-          echo "terraform init -backend-config=environments/${{ inputs.environment }}/backend.hcl"
-          terraform init -backend-config=environments/${{ inputs.environment }}/backend.hcl
-
-      - name: Terraform Plan
-        id: tf-plan
-        working-directory: terraform
-        run: |
-          set -o pipefail
-          exitcode=0
-          tfargs="-detailed-exitcode"
-          echo "terraform plan -var-file=environments/${{ inputs.environment }}/terraform.tfvars -var="blue_image_tag=${{ inputs.blue_image_tag }}" -var="green_image_tag=${{ inputs.green_image_tag }}" $tfargs | tee tfplan.txt || exitcode=$?"
-          terraform plan -var-file=environments/${{ inputs.environment }}/terraform.tfvars -var="blue_image_tag=${{ inputs.blue_image_tag }}" -var="green_image_tag=${{ inputs.green_image_tag }}" $tfargs | tee tfplan.txt || exitcode=$?
-          echo "exitcode=${exitcode}"  # 0=clean plan, 1=error, 2=stuff in plan
-          echo "exitcode=${exitcode}" >> $GITHUB_OUTPUT
-          (( exitcode == 1 )) && exit 1 || exit 0
-
   # Determine whether the active colour should be switched before or after the Terraform apply
   deployment-order:
     name: Determine deployment order - ${{ inputs.environment }}
@@ -388,6 +339,55 @@ jobs:
             echo ""
             echo "$MESSAGE"
           } >> "$GITHUB_STEP_SUMMARY"
+
+  plan:
+      name: Plan - ${{ inputs.environment }}
+      runs-on: ubuntu-latest
+      needs: display-versions
+      outputs:
+        plan_exitcode: "${{ steps.plan.outputs.exitcode }}"
+      environment: ${{ inputs.environment }}-plan
+      strategy:
+        fail-fast: false
+      permissions:
+        id-token: write
+        contents: read
+      steps:
+        - name: Checkout Repository
+          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
+        - name: Configure AWS Credentials
+          uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
+          with:
+            role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd"
+            role-session-name: "hmpps-cr-ancillary-jitbit-app-${{ github.run_number }}"
+            aws-region: "eu-west-2"
+
+        - name: Setup Terraform
+          uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
+          with:
+            terraform_version: "1.10.0"
+            terraform_wrapper: false
+
+        - name: Terraform Init
+          working-directory: terraform
+          run: |
+            terraform --version
+            echo "terraform init -backend-config=environments/${{ inputs.environment }}/backend.hcl"
+            terraform init -backend-config=environments/${{ inputs.environment }}/backend.hcl
+
+        - name: Terraform Plan
+          id: tf-plan
+          working-directory: terraform
+          run: |
+            set -o pipefail
+            exitcode=0
+            tfargs="-detailed-exitcode"
+            echo "terraform plan -var-file=environments/${{ inputs.environment }}/terraform.tfvars -var="blue_image_tag=${{ inputs.blue_image_tag }}" -var="green_image_tag=${{ inputs.green_image_tag }}" $tfargs | tee tfplan.txt || exitcode=$?"
+            terraform plan -var-file=environments/${{ inputs.environment }}/terraform.tfvars -var="blue_image_tag=${{ inputs.blue_image_tag }}" -var="green_image_tag=${{ inputs.green_image_tag }}" $tfargs | tee tfplan.txt || exitcode=$?
+            echo "exitcode=${exitcode}"  # 0=clean plan, 1=error, 2=stuff in plan
+            echo "exitcode=${exitcode}" >> $GITHUB_OUTPUT
+            (( exitcode == 1 )) && exit 1 || exit 0
 
   deploy:
     name: Deploy - ${{ inputs.environment }}
